src/ComicBookGallery/Models/Artist.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ComicBookGallery.Models
{
    public class Artist
    {
        public string Name { get; set; }
        public string Role { get; set; }
    }
}

src/ComicBookGallery/Models/ComicBook.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ComicBookGallery.Models
{
    public class ComicBook
    {
        public int Id { get; set; }
        public Series Series { get; set; }
        public int IssueNumber { get; set; }
        public string DescriptionHtml { get; set; }
        public Artist[] Artists { get; set; }
        public bool Favorite { get; set; }
        public string DisplayText
        {
            get
            {
                if (Series != null)
                    return Series.Title + " #" + IssueNumber;
                else
                    return null;
            }
        }
        //series-title-issunumber.jpg
        public string CoverImageFileName
        {
            get
            {
                if (Series != null)
                    return Series.Title.Replace(" ", "-").ToLower()
                        + "-" + IssueNumber + ".jpg";
                else
                    return null;
            }
        }
    }
}

src/ComicBookGallery/Models/Series.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ComicBookGallery.Models
{
    public class Series
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string DescriptionHtml { get; set; }
        public ComicBook[] Issues { get; set; }
    }
}

src/ComicBookGallery/Controllers/ComicBooksController.cs
using ComicBookGallery.Models;
using ComicBookGallery.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace ComicBookGallery.Controllers
{
    public class ComicBooksController : Controller
    {
        private ComicBookRepository _comicBookRepository = null;

        public ComicBooksController() {
            _comicBookRepository = new ComicBookRepository();
        }

        public ActionResult Index()
        {
            ComicBook[] comicBooks = _comicBookRepository.GetComicBooks();

            return View(comicBooks);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            ComicBook comicBook = _comicBookRepository.GetComicBook((int)id);

            return View(comicBook);
        }
    }
}

src/ComicBookGallery/Views/ComicBooks/Details.cshtml
@model ComicBookGallery.Models.ComicBook
@{
    ViewBag.Title = Model.DisplayText;
    ViewBag.ShowBackBar = true;
}
    <div class="container">
    <h2>@Model.DisplayText</h2>
        <div class="row">
            <div class="col-md-6">
                <div class="well">
                    <h5><label>Series Title:</label>@(Model.Series != null ? Model.Series.Title : "N/A")</h5>
                    <h5><label>Issue #:</label> @Model.IssueNumber</h5>
                    <h5><label>Favorite:</label> @if (Model.Favorite) { <span>Yes</span>} else { <span>No</span> }</h5>
                    <h5>Artists:</h5>
                        @if (Model.Artists.Length > 0)
                        {
                            <ul>
                                @foreach (var artist in Model.Artists)
                                {
                                    <li>@artist.Role - @artist.Name</li>
                                }
                            </ul>

                        }
                    </div>
                    <h5>Description</h5>
                    @Html.Raw(Model.DescriptionHtml)
                </div>
            <div class="col-md-6">
                <img src="/Images/@Model.CoverImageFileName"
                     alt="@Model.DisplayText" class="img-responsive" />
            </div>
      </div>
</div>

src/ComicBookGallery/Views/ComicBooks/Index.cshtml
@model ComicBookGallery.Models.ComicBook[]

@{
    ViewBag.Title = "Comic Books";
    ViewBag.ShowBackBar = false;
}
<h2><b>@ViewBag.Title</b></h2>
<div class="row well">
    @{
        foreach (var comicBook in Model)
        {
            <div class="col-md-3">
                <h5><b>@Html.ActionLink(comicBook.DisplayText,"Details", new { id = comicBook.Id })</b></h5>
                <a href="@Url.Action("Details",new { id = comicBook.Id })">
                    <img src="/Images/@comicBook.CoverImageFileName" alt="@comicBook.DisplayText"class="img-responsive" />
                </a>
            </div>
        }
    }
    
</div>

src/ComicBookGallery/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Comic Book Gallery</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/site.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Comic Book Gallery", "Index", "ComicBooks", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <!-- Add menu items here -->
                </ul>
            </div>
        </div>
    </div>
    @if(ViewBag.ShowBackBar != null && ViewBag.ShowBackBar)
    {
        <div class="backbar">
            <div class="container">
                @Html.ActionLink("Go to All Comic Books", "Index", null, new { @class = "btn btn-default"})
            </div>
        </div>
    }
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Comic Book Gallery</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</body>
</html>